version: '3'

services:
  php-apache:
    build:
      context: ./docker/php-apache
      args:
        - PHP_VERSION=7.1
    environment:
      LANG: en_US.UTF-8
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - .:/var/www/html
    networks:
     - appnet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - mysqldata:/var/lib/mysql
    ports:
     - "${MYSQL_PORT:-33066}:3306"
    networks:
     - appnet

volumes:
  mysqldata:

networks:
  appnet:
    driver: bridge